version: '2'
services:
    php:
      build: ./
      image: php:7.2-fpm-composer-stretch
      container_name: sflex.php
      volumes:
        - .:/var/www/html
      restart: always
      expose:
        - 9000
      entrypoint: /var/www/html/etc/entrypoint.sh

    nginx:
      container_name: sflex.nginx
      image: nginx:latest
      ports:
        - "8082:80"
      depends_on:
        - php
      volumes_from:
        - php:ro
      restart: always
      volumes:
        - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro

